"""add phone_number

Revision ID: 7a92bbc34a61
Revises: b40f2e67bb1b
Create Date: 2023-03-02 14:02:18.896774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a92bbc34a61'
down_revision = 'b40f2e67bb1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'phone_number')
    # ### end Alembic commands ###
