"""add phone_number

Revision ID: fc56baa5fa03
Revises: 7a92bbc34a61
Create Date: 2023-03-02 14:04:09.852120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc56baa5fa03'
down_revision = '7a92bbc34a61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'phone_number', sa.String(), nullable=True))
    op.drop_column('votes', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('phone_number',
                  sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
